In [10]:
import numpy as np

## 向量的基本运算

In [11]:
# 定义一个向量
x = np.array([2, 5, 8])
print(x)

[2 5 8]


In [12]:
print(x.shape)

(3,)


In [13]:
# 1. 向量转置
print(x.T)
print(x.T.shape)

[2 5 8]
(3,)


In [16]:
# 2. 向量相加
y = np.array([1, 3, 7])
print(x + y)

[ 3  8 15]


In [17]:
print(x + 5)

[ 7 10 13]


In [18]:
# 3. 向量相乘
# 与标量相乘
print(x * 3)

[ 6 15 24]


In [19]:
# 与向量相乘
print(x * y)

[ 2 15 56]


In [20]:
# 4. 向量点积（内积）
print(x.dot(y))

73


## 向量范数

In [22]:
# L0范数
norm_l0 = np.linalg.norm(x, ord=0)
print(norm_l0)

3.0


In [23]:
# L1范数
norm_l1 = np.linalg.norm(x, ord=1)
print(norm_l1)

15.0


In [26]:
# L2范数
norm_l2 = np.linalg.norm(x, ord=2)
print(norm_l2)

9.643650760992955


In [27]:
# 无穷范数
norm_inf = np.linalg.norm(x, ord=np.inf)
print(norm_inf)

8.0
