In [2]:
import numpy as np

In [6]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,3,7],[5,0,2]])

In [10]:
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
# 1. 转置
print(A.T)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [15]:
# 2. 矩阵相加
print(A + B)

[[ 2  5 10]
 [ 9  5  8]]


In [18]:
print((A + B).T)
print(A.T + B.T)

[[ 2  9]
 [ 5  5]
 [10  8]]
[[ 2  9]
 [ 5  5]
 [10  8]]


In [20]:
# 3. 矩阵与标量相加
print(A + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [22]:
# 4. 矩阵与向量相加
x = np.array([2,4,6])
print(A + x)

[[ 3  6  9]
 [ 6  9 12]]


In [24]:
# 5. 矩阵与标量相乘
print(A * 3)

[[ 3  6  9]
 [12 15 18]]


In [25]:
# 6. 矩阵与向量相乘
print(A * x)

[[ 2  8 18]
 [ 8 20 36]]
