In [7]:
import numpy as np

## 矩阵及其运算

In [8]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,3,7],[5,0,2]])

In [18]:
print(A)
print(B)
print(A.shape)

[[1 2 3]
 [4 5 6]]
[[1 3 7]
 [5 0 2]]
(2, 3)


In [10]:
# 1. 转置
print(A.T)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [11]:
# 2. 矩阵相加
print(A + B)

[[ 2  5 10]
 [ 9  5  8]]


In [12]:
print((A + B).T)
print(A.T + B.T)

[[ 2  9]
 [ 5  5]
 [10  8]]
[[ 2  9]
 [ 5  5]
 [10  8]]


In [13]:
# 3. 矩阵与标量相加
print(A + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [14]:
# 4. 矩阵与向量相加
x = np.array([2,4,6])
print(A + x)

[[ 3  6  9]
 [ 6  9 12]]


In [15]:
# 5. 矩阵与标量相乘
print(A * 3)

[[ 3  6  9]
 [12 15 18]]


In [16]:
# 6. 矩阵与向量相乘
print(A * x)

[[ 2  8 18]
 [ 8 20 36]]


In [78]:
# 7. 矩阵与矩阵相乘(阿达玛积，两个矩阵对应元素乘积，计算出的矩阵形状不变)
print(A * B)

[[ 1  6 21]
 [20  0 12]]


In [47]:
# 8. 矩阵乘法（点积）
print(A.dot(B.T))

[[28 11]
 [61 32]]


In [26]:
print(A @ B.T) # 与 A.dot(B.T) 一样，也是矩阵乘法

[[28 11]
 [61 32]]


In [28]:
print(B.T @ A)

[[21 27 33]
 [ 3  6  9]
 [15 24 33]]


In [30]:
print((A @ B.T).T)

[[28 61]
 [11 32]]


In [32]:
print(B @ A.T)

[[28 61]
 [11 32]]


In [35]:
# 9. 矩阵求逆
C = np.array([[1,2],[3,5]])
print(C)

[[1 2]
 [3 5]]


In [44]:
C_inv = np.linalg.inv(C) # 方阵求逆函数
print(C_inv)

[[-5.  2.]
 [ 3. -1.]]


In [46]:
print(C @ C_inv)
print(C_inv @ C)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[1.00000000e+00 2.22044605e-16]
 [1.11022302e-16 1.00000000e+00]]


In [49]:
C_inv = np.around(C_inv).astype(int)
print(C_inv)

[[-5  2]
 [ 3 -1]]


In [50]:
print(C @ C_inv)
print(C_inv @ C)

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


In [56]:
A_inv = np.linalg.pinv(A) # 伪逆
print(A_inv)

[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [60]:
print(A @ A_inv) # 矩阵与伪逆点积计算的结果是单位矩阵

[[ 1.00000000e+00 -2.77555756e-16]
 [-1.11022302e-15  1.00000000e+00]]


In [62]:
print(A_inv @ A) # 伪逆与矩阵点积计算的结果不是单位矩阵

[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


In [64]:
# 10. 获取矩阵元素
print(A[0][1])

2


In [66]:
print(A[0,1])

2


In [68]:
# 11. 矩阵向量化
print(A.flatten()) # 行向量化

[1 2 3 4 5 6]


In [77]:
# 12. 矩阵内积 （两个矩阵对应元素乘积之和。是一个标量）
# 利用阿达玛积 （两个矩阵各位置元素相乘，形状不变）
print(A * B)
print(np.sum(A * B))

[[ 1  6 21]
 [20  0 12]]
60


In [76]:
# 利用向量化
print(np.dot(A.flatten(), B.flatten())) # np.dot(A.flatten(), B.flatten()) 两个向量作点积运算，即各位置元素对应相乘，再求和

60


In [80]:
# 13. 矩阵克罗内克积（张量积）
print(np.kron(A, B))

[[ 1  3  7  2  6 14  3  9 21]
 [ 5  0  2 10  0  4 15  0  6]
 [ 4 12 28  5 15 35  6 18 42]
 [20  0  8 25  0 10 30  0 12]]


## 张量(tensor)

In [81]:
tensor = np.array([[[1,3,5,7],[2,4,6,8],[3,6,9,12]],[[0,3,2,7],[2,9,4,12],[3,5,9,2]]])

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [83]:
print(tensor)

[[[ 1  3  5  7]
  [ 2  4  6  8]
  [ 3  6  9 12]]

 [[ 0  3  2  7]
  [ 2  9  4 12]
  [ 3  5  9  2]]]


In [85]:
print(tensor.shape) # 2个矩阵 每个矩阵是3行4列

(2, 3, 4)
