In [2]:
import numpy as np

## 均匀分布

In [9]:
# 1. [0, 1) 分布的小数
a = np.random.rand(5) # 向量
print(a)

[0.5701376  0.27952253 0.24456365 0.89166881 0.50549568]


In [14]:
a = np.random.rand(2, 3) * 10 + 10 # 矩阵，每个元素在 [10, 20) 之间
print(a)

[[15.64568637 18.05484985 19.96100887]
 [11.94221412 11.01350516 18.43229381]]


In [31]:
# 2. 整数
b = np.random.randint(0, 100, size=[2, 3])
print(b)

[[45 59 26]
 [23 94 86]]


## 正态分布

In [34]:
# 1. 标准正态分布
c = np.random.randn(10) # 10个数构成的向量，每一个元素服从标准正态分布。均值为0，方差为1，都集中在0附近，离0越近，可能性越大
print(c)

[-0.36457873  1.42332041 -0.01665086 -1.13357358 -0.4394942  -0.39373055
  0.40243375 -2.03826985 -1.59236442  0.90519577]


In [39]:
c = np.random.randn(10) * 10 + 5 # 以 5 为均值，方差是10，一般正太分布，分布较广
print(c)

[ -2.1742385    8.9910366   -1.3032422  -20.20482192  -3.85164929
  13.55219024 -13.60790339   6.34950693  19.65620508  -0.13124325]


In [40]:
# 2. 一般正态分布
d = np.random.normal(5, 10, size=(2, 3)) # 均值=5，方差=10
print(d)

[[10.92284552 16.41189993 16.14039731]
 [ 9.39827756  7.3793175  21.73823653]]
